GET http://localhost:8080/v1/rest-example-one/Merhaba Dev/230ced7e-0eae-472f-b768-752ffbaf74b4/5
Accept: application/json

###
GET http://localhost:8080/v1/rest-example-one/request-param?stringValue=Merhaba Dev&uuidValue=230ced7e-0eae-472f-b768-752ffbaf74b4&integerValue=5
Accept: application/json

###
GET http://localhost:8080/v1/rest-example-one/like-request-param?stringValue=Merhaba Dev&uuidValue=230ced7e-0eae-472f-b768-752ffbaf74b4&integerValue=5
Accept: application/json

###
GET http://localhost:8080/v1/rest-example-one/request-param-not-required?stringDifferentValueName=Merhaba Dev&integerValue=5
Accept: application/json

###
GET http://localhost:8080/v1/rest-example-one/request-param-not-required?stringDifferentValueName=Merhaba Dev&integerValue=5
Accept: application/json

###
